### PR TITLE
[FIX] Easy setup

### PR DESCRIPTION
**Pull request by Karajan421**
The main purpose of this  PR is to fix the little mistakes that slipped through the cracks during the last one. 

**Issues fixed:**
- The .env.example now features the correct model path format (I let a concrete example in, but we could use a template if you guys prefer) 
- Updated the setup.sh / dockerfile / requirements.txt to use a llama-cpp-version allowing 3B models loading 
- Fixed a bug that caused the search function to not be included in the guidance program when running with both ethics and test mode off

Another small PR, but getting us closer to a plug-and-play install :)

### CODE REVIEW

**Review by iGavroche — CHANGES_REQUESTED** [review]
could you make the local requirements the default ones and change the other one to be `docker_requirements. txt`.

Also, do we need to mention the setup steps in the Readme?

**Comment by Karajan421** [comment]
Ah yes, I will do that! And you're right we should feature this in the readme, I'll propose an update :)

**Review by iGavroche — APPROVED** [review]

**Comment by Karajan421** [comment]
For the requirements file, I propose something even simpler: both the local and docker installation use the same requirements.txt  file (that are both completed by commands in the dockerfile and the setup.sh respectively)

**Review by iGavroche — APPROVED** [review]
very nice!

**Pull request merged**
